name: Deploy app to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to DockerHub
        run: echo "${{secrets.DOCKER_PASSWORD}}" | docker login -u "${{secrets.DOCKER_USERNAME}}" --password-stdin

      - name: Build and Publish Docker Image
        run: |
          docker build -t kharel2054/todo-app:${{ github.sha }} .
          docker push kharel2054/todo-app:${{ github.sha }}

      - name: Setup Terraform 
        uses: hashicorp/setup-terraform@v1

      - name: Login to Azure
        env:
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        run: |
          az login --service-principal --username $AZURE_CLIENT_ID --password $AZURE_CLIENT_SECRET --tenant $AZURE_TENANT_ID

      - name: Terraform Init
        env:
          TF_VAR_ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          TF_VAR_ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          TF_VAR_ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          TF_VAR_ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          TF_VAR_ARM_ACCESS_KEY: ${{ secrets.ARM_ACCESS_KEY }}
        run: terraform init

      - name: Terraform plan
        run: terraform plan

      - name: Terraform apply
        env:
          TF_VAR_ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          TF_VAR_ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          TF_VAR_ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          TF_VAR_ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          TF_VAR_ARM_ACCESS_KEY: ${{ secrets.ARM_ACCESS_KEY }}
        run: terraform apply -auto-approve

      - name: Setup Kubectl
        uses: azure/setup-kubectl@v4
        with: 
          version: '1.31'

      - name: Get Kubernetes Credentials
        run: |
          az aks get-credentials --resource-group todoapprg --name todoappcluster  

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml

