name: Deploy app to Kubernetes

on:
  push:
    branches:
      - main


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to DockerHub
        run: echo "${{secrets.DOCKER_PASSWORD}}" | docker login -u "${{secrets.DOCKER_USERNAME}}" --password-stdin

      - name: Build and Publish Docker Image
        run: |
          docker build -t kharel2054/todo-app:${{ github.sha }} .
          docker push kharel2054/todo-app:${{ github.sha }}

      - name: Setup Terraform 
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_ACCESS_KEY: ${{ secrets.ARM_ACCESS_KEY }}

        run: terraform init


      - name: Terraform plan
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_ACCESS_KEY: ${{ secrets.ARM_ACCESS_KEY }}

        run: terraform plan -input=false


      - name: Terraform apply
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_ACCESS_KEY: ${{ secrets.ARM_ACCESS_KEY }}

        run: |
          az login --service-principal --username $ARM_CLIENT_ID --password $ARM_CLIENT_SECRET --tenant $ARM_TENANT_ID
          terraform apply -input=false -auto-approve

      - name: Setup Kubectl
        uses: azure/setup-kubectl@v1
        with: 
          version: '1.31'

      - name: Get Kubernetes Credentials
        run: |
          az aks get-credentials --resource-group todoapprg --name todoappcluster  

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml